services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data/logstore:/app/data/logstore

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    environment:
      LOGSTORE_API_BASE_URL: http://backend:8080
    depends_on:
      - backend
    ports:
      - "3000:3000"
