<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.0</version>
        <relativePath/>
    </parent>

    <groupId>io.github.sauravjaiswalsj</groupId>
    <artifactId>logstore-parent</artifactId>
    <version>0.1.0</version>
    <packaging>pom</packaging>

    <name>LogStore</name>
    <description>Embedded-first append-only log store alpha</description>
    <url>https://github.com/sauravjaiswalsj/LogStore</url>
    <inceptionYear>2026</inceptionYear>

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>sauravjaiswalsj</id>
            <name>Saurav Jaiswal</name>
            <url>https://github.com/sauravjaiswalsj</url>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:https://github.com/sauravjaiswalsj/LogStore.git</connection>
        <developerConnection>scm:git:ssh://git@github.com/sauravjaiswalsj/LogStore.git</developerConnection>
        <url>https://github.com/sauravjaiswalsj/LogStore</url>
        <tag>HEAD</tag>
    </scm>

    <modules>
        <module>logstore-core</module>
        <module>logstore-server</module>
        <module>logstore-benchmarks</module>
    </modules>

    <properties>
        <java.version>23</java.version>
        <lombok.version>1.18.38</lombok.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>${java.version}</maven.compiler.release>
        <maven.deploy.skip>true</maven.deploy.skip>
    </properties>
</project>
